---
- name: Festplattenplatz prüfen
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Ausgabe von df -h sammeln
      ansible.builtin.command: df -h
      register: diskspace_output

    - name: Diskspace anzeigen
      ansible.builtin.debug:
        var: diskspace_output.stdout_lines
